# Generated by Django 4.2.6 on 2023-11-14 19:22

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['due_date']},
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 14, 19, 22, 33, 198796, tzinfo=datetime.timezone.utc))]),
        ),
    ]
