# Generated by Django 4.2.6 on 2023-11-14 19:24

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_options_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 14, 19, 24, 4, 805554, tzinfo=datetime.timezone.utc))]),
        ),
    ]
