# Generated by Django 4.2.6 on 2023-11-14 20:50

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 14, 20, 50, 28, 259175, tzinfo=datetime.timezone.utc))]),
        ),
    ]
