# Generated by Django 4.2.6 on 2023-11-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
    ]
