# Generated by Django 4.2.6 on 2023-11-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_notification'),
        ('tasks', '0005_remove_invitation_code_alter_invitation_status'),
        ('tasks', '0008_alter_task_due_date'),
    ]

    operations = [
    ]
