# Generated by Django 4.2.6 on 2023-11-22 20:45
# Generated by Django 4.2.6 on 2023-11-23 14:01


import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_merge_20231117_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 22, 20, 45, 13, 247814, tzinfo=datetime.timezone.utc))]),
        ),
    ]
