# Generated by Django 4.2.6 on 2023-11-17 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_merge_20231117_1339'),
    ]

    operations = [
    ]
