# Generated by Django 4.2.6 on 2023-11-29 13:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.invitation'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 29, 13, 48, 1, 722461, tzinfo=datetime.timezone.utc))]),
        ),
    ]
