# Generated by Django 4.2.6 on 2023-12-01 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_alter_task_due_date'),
        ('tasks', '0013_task_is_complete_alter_task_due_date'),
    ]

    operations = [
    ]
