# Generated by Django 4.2.6 on 2023-11-30 23:25

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_task_is_complete_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_archived',
            field=models.BooleanField(blank='false', default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 11, 30, 23, 25, 0, 101745, tzinfo=datetime.timezone.utc))]),
        ),
    ]
