# Generated by Django 4.2.6 on 2023-12-01 09:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_points_alter_task_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_tasks_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 12, 1, 9, 31, 54, 672564, tzinfo=datetime.timezone.utc))]),
        ),
    ]
