# Generated by Django 4.2.6 on 2023-12-01 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_notification_invitation_alter_task_due_date"),
        ("tasks", "0014_merge_20231201_1335"),
        ("tasks", "0016_user_total_tasks_completed_alter_task_due_date"),
    ]

    operations = []
