# Generated by Django 4.2.6 on 2023-12-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_notification_invitation_alter_task_due_date'),
        ('tasks', '0017_merge_20231201_1342'),
    ]

    operations = [
    ]
