# Generated by Django 4.2.6 on 2023-12-01 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_merge_20231201_1357'),
        ('tasks', '0018_merge_20231201_1343'),
    ]

    operations = [
    ]
