# Generated by Django 4.2.6 on 2023-12-01 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_merge_20231201_1432'),
        ('tasks', '0019_merge_20231201_1416'),
    ]

    operations = [
    ]
