# Generated by Django 4.2.6 on 2023-12-04 12:31

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_merge_20231201_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.datetime(2023, 12, 4, 12, 31, 7, 863019, tzinfo=datetime.timezone.utc))]),
        ),
    ]
